### ISSUE TITLE
Conflict of jQuery UI version

### ISSUE THREAD

**Issue by prsolucoes** [yiisoft/yii2-jui#89] opened 2019-08-14 18:38 UTC
### What steps will reproduce the problem?

Im trying install latest admin-lte: 2.4.17.

### What's expected?

AdminLTE installed with success.

### What do you get instead?

Error:

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-jui 2.0.7 requires bower-asset/jquery-ui ~1.12.1 -> satisfiable by bower-asset/jquery-ui[1.12.1].
    - yiisoft/yii2-jui 2.0.7 requires bower-asset/jquery-ui ~1.12.1 -> satisfiable by bower-asset/jquery-ui[1.12.1].
    - Can only install one of: bower-asset/jquery-ui[1.11.4, 1.12.1].
    - Can only install one of: bower-asset/jquery-ui[1.11.4, 1.12.1].
    - bower-asset/admin-lte v2.4.17 requires bower-asset/jquery-ui 1.11.4 -> satisfiable by bower-asset/jquery-ui[1.11.4].
    - Installation request for bower-asset/admin-lte 2.4.17 -> satisfiable by bower-asset/admin-lte[v2.4.17].
    - Installation request for yiisoft/yii2-jui 2.0.7 -> satisfiable by yiisoft/yii2-jui[2.0.7].
```

And im using in my composer.json:

```
"bower-asset/admin-lte": "2.4.17",
		"bower-asset/font-awesome": "4.7.0",
		"bower-asset/html5shiv": "3.7.3",
		"bower-asset/jquery": ">=1.9.0 <4.0.0",
		"bower-asset/jquery-slimscroll": "1.3.8",
		"bower-asset/js-cookie": "2.2.1",
		"bower-asset/lightbox2": "2.11.1",
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.25
| PHP version      | 7
| Operating system  | macos/linux

**Comment by samdark** [comment] 2019-08-15 09:08
Duplicate of https://github.com/yiisoft/yii2-debug/issues/406

**Comment by samdark** [comment] 2019-08-20 15:14
The version 1.12.0 has many breaking changes and current code is not compatible with 1.11.4.

That is a bug in admin-lte package. See that npm has [constraint specified correctly](https://github.com/ColorlibHQ/AdminLTE/blob/v2.4.17/package.json#L51) while [bower one is outdated](https://github.com/ColorlibHQ/AdminLTE/blob/v2.4.17/bower.json#L58).

**Comment by samdark** [comment] 2019-08-20 15:15
https://github.com/ColorlibHQ/AdminLTE/issues/2209. Closing issue here since fix is being prepared.

**Closed by samdark** 2019-08-20 15:15 UTC
